name: RPG
description: RPG
author: StarTux
version: 0.1
main: com.winthier.rpg.RPGPlugin
depend: [ Custom, Exploits, GenericEvents ]
commands:
  rpg:
    description: rpg
    permission: rpg.rpg
permissions:
  rpg.rpg:
    description: Use /rpg
